### ISSUE TITLE
Unable to view Admin at localhost:8001

### ISSUE THREAD

**Issue by dondreytaylor** [StreamMachine/StreamMachine#32]
Really like the direction of your project. I do however have one question. When I install StreamMachine and execute the command  `./streammachine-cmd --config ./config/standalone.json` from within the repository directory, I'm unable to view the admin at http://localhost:8001/admin within the browser. Instead, it says "invalid stream". Is there something I'm doing wrong. Your feedback or anyone else's is greatly appreciated. 

Thanks

**Comment by ewr** [comment]
That's because it's gone! It got yanked in f5647761deb611d7a98f1eca384dac1eaa5ab26e in favor of just fleshing out the API endpoints. The UI side hadn't been keeping up with underlying changes, and added a large dependency stack to the project. In standalone mode, your API endpoints should be available under `/api`, so `/api/streams`, etc. There isn't currently API documentation, but if you take a look at this code I would hope that it is largely self-explanatory:

https://github.com/StreamMachine/StreamMachine/blob/af8d5fea13ac72cb627f7b292b640111144fd9f5/src/streammachine/master/admin/api.coffee#L58-L189

Where in the docs did you see that admin UI reference? I should update it.

I would definitely be open to recreating the admin UI as a separate project. In our day-to-day operation, though, it didn't turn out to be super-useful: how often do you end up updating your stream settings in production?

**Comment by dondreytaylor** [comment]
Oh wow the script you linked me is a big help, clarifies a lot! I probably should have asked this question under the StreamMachine cookbook repository, that's where I saw the reference to the admin UI. You can find it directly under the section titled "Vagrant". Instead of using the cookbook I tried to set up the same on my local machine.

https://github.com/StreamMachine/streammachine-cookbook

Regarding using stream settings in production, I'm quite new to using nodejs to stream audio and I figured the admin would give me a better insight to how things work.

**Comment by ewr** [comment]
Thanks. I'll clean up those docs on the cookbook repo.

Feel free to ask any questions here as issues or email me directly. Docs are definitely StreamMachine's weakest point.
