### ISSUE TITLE
Missing starting segments for icecast input source

### ISSUE THREAD

**Issue by fatihsokmen** [StreamMachine/StreamMachine#57]
I am using standalone.json config (bundled with code) to run streammachine (default test stream)
Then, an app captures pcm voice, encodes (mp3) and sends stream machine as icecast input source.
Server prints log incoming ice source info and initializes  rewindbuffer. Till now, everything is fine

When I request running HLS stream from browser as /test.m3u8 I have to wait for a while (prints "No data" when request) and can not get  first segments.

Sample M3U is:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:2
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-INDEPENDENT-SEGMENTS
#EXTINF:10.08,
#EXT-X-PROGRAM-DATE-TIME:2015-10-21T18:42:41.132+00:00
/test/ts/2.mp3?session_id=3f067e38-0c07-4800-8ccb-7f5f80a4d55d

What could be reason for missing segments ?

**Comment by ewr** [comment]
This is actually part of the implementation of a feature, but I'd be glad to hear more about your use case and see if we can make the two work.

Basically we don't list the two segments in the very front of the buffer in the index, so that they don't fall out of the index and become unavailable at the same time. Imagine a client downloads an index right as a segment is being expired, leaving it listed in the index but not available for download.

The missing segments don't matter for our radio use case, where you have an infinite stream that you're always going to be truncating somewhere.

Are you actually hoping to use the HLS more as an event broadcast, where a client would start at the beginning and move forward rather than playing from the "live" position?

**Comment by fatihsokmen** [comment]
Thanks for quick prompt. As you said , it is not going to be a problem for an infinite stream.

I wanted to broadcast variable length (from seconds to hours) but complete **live** streams and clients would always play live position. I am not sure **streammachine** is the rigth middleware for dynamically create and delete such live streams on the fly. I also tested rest APIs and worked fine in basic test.

**Comment by ewr** [comment]
There's nothing inherently unsupportable about that use case, but you're right that streammachine might not be the best tool for it. 

You would need to tweak the index logic you hit (not hard), and then basically turn off the code that handles capping the max length of the rewind buffer. And then our code is also more tuned for a small number of long-lived stable streams, so I haven't tested large numbers of dynamic streams.

I do eventually like the use case of supporting live events rather than just continuous broadcasts (we do a decent number of events as a station), but I couldn't say when or if that would be something I would get to work on.

**Comment by fatihsokmen** [comment]
I will work on that. Thanks for quick support again.

**Comment by ewr** [comment]
:+1: I'm going to close this issue, but feel free to comment here or email if you end up working on it and have questions.

**Comment by fatihsokmen** [comment]
I can now run short index file starting from 0 and indexer works fine. But first segment "0.mp3" always returns empty content (zero byte) while "1" and further segments don't. (Not a 'No data' case)
Any idea ?
