### ISSUE TITLE
Unable to Stream via VLC

### ISSUE THREAD

**Issue by 5punk** [StreamMachine/StreamMachine#88]
Hi,
I am trying to stream music to port 8002 with vlc.
I was following the Getting Started wiki.
However, when I run: 
`cvlc music.mp3 --sout '#standard{mux=dummy,dst=source:testing@0.0.0.0:8002/test,access=shout}' --http-password=GUIPassword -I http`

I get the following errors

```
21914/master -- event: Inactive source disconnected. source_mount=test
21914/master -- error: useSource failed to get switchover within five seconds. new_source=Icecast (::ffff:127.0.0.1:52874), old_source=undefined, source_mount=test
```

And when I point VLC to a folder with multiple mp3 files, I get the errors

```
[mp3 @ 0xb07ed140] Header missing
[mp3 @ 0xb07ed140] Header missing
[mp3 @ 0xb07ed140] Header missing
21914/master -- error: useSource failed to get switchover within five seconds. n  ew_source=Icecast (::ffff:127.0.0.1:52883), old_source=undefined, source_mount=t  est
```

I have searched through all the open and closed issues and was unable to find an answer.
Any help would be *greatly* appreciated.

**Comment by 5punk** [comment]
I've figured it out.
I've updated the documentation to help others who have been frantically looking for help, I've also added documentation to allow playlists, multiple mp3 files and directories :)

https://github.com/StreamMachine/StreamMachine/wiki/Setting-up-a-local-stream-with-VLC-or-LiquidSoap

**Comment by amerireza** [comment]
I also have problem and I use this command line to stream, but I can not get it write.
`cvlc --repeat tmp.mp3 --sout '#standard{mux=dummy,dst=source:test@0.0.0.0:8002/test,access=shout}' --http-password=pass -I http`

my config on standalone.json is:
```
{
        "port":         8001,
        "source_port":  8002,
  "api_port":     8003,
        "log": {
                "stdout":     true
  },
  "streams": {
    "test": {
      "key":              "test",
      "root_route":       true,
      "format":           "mp3",
      "seconds":          3600,
      "metaTitle":        "test",
      "host":             "localhost",
      "source_password":  "test"
    }
  }
}
```
I am wondering may be the problem is the "source" word in the cvlc command line, isn't it?

**Comment by cdgraff** [comment]
Hi! I recommend try with butt (https://danielnoethen.de/) is tested and support in StreamMachine

Or other good option to test is use fallback feature, you can relay any icecast radio stream into your StreamMachine installation.

Btw, our fork have many improvements (https://github.com/mediainbox/StreamMachine)

**Comment by swordsreversed** [comment]
Hi @amerireza, I also thought it must be the word source, it is really hard to know if "source" is supposed to be a variable (name of the source/stream) or the word "source". Neither worked for me. This did work with ffmpeg:

```
ffmpeg -i dusty.mp3 -legacy_icecast 1 -ice_name "DemoStream" -f mp3 icecast://mystream:coolpassword@11.11.111.11:8000/mystream 
```

I ended up using BUTT as well, due to its windows support and ease of use.

Also admin has been removed, I had to search through the issues to find that. There is a pull request by @5punk updating the docs but it's stuck because it looks like this project is abandoned.

@cdgraff thanks for your fork, can you tell us what the improvements are? It's not the documentation obviously :)

**Comment by cdgraff** [comment]
@swordsreversed i think the most important improvements be:

- GeoLock feature: Now is possible WhiteList/BlackList country codes that hit the stream, and setting a custom Fallback for this condition to response with a audio message customized in case this this condition
- Master fallback: Into slave can define a Array of Master Nodes, in case primary fail can slaves connect to backup node
- A lot of updates related to older library used into original sources, that after some years be older and show some deprecation issues, allowing to run into new versions of Node.

On the other side we'll continue supporting StreamMachine as is the core of others comercial product we build on top.

Hope Eric (creator of this amazing MediaServer) an back to support the project soon, we work with them a few months ago and his knowledge and vision to made grow this product be amazing

**Comment by amerireza** [comment]
Thanks all,

@swordsreversed I couldn't use butt either! can you send me an image or your config?

**Comment by amerireza** [comment]
I changed my cvlc command to the line below but it still have errors.

`$ cvlc --repeat Desktop/tmp.mp3 --sout transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:std{access=shout,mux=ogg,dst=source:test@localhost:8002/test :display :sout-all :sout-keep}' --http-password=pass -I http`

the log: 

```
VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)
[0x12ed5a8] [http] lua interface: Lua HTTP interface
[0x7fa578050c48] mux_ogg mux: Open
notification: Speex header too small
[0x7fa578050c48] mux_ogg mux: Close
```

it still does not work :((

**Comment by swordsreversed** [comment]
@amerireza don't use VLC, it doesn't seem to work with this software anymore. Did you try ffmpeg? With Butt just select Icecast and add your port, password and stream name.

![screen shot 2016-10-31 at 11 31 12](https://cloud.githubusercontent.com/assets/2155844/19841297/9f3b2ab6-9f5d-11e6-94b3-659ea3f54808.png)

**Comment by amerireza** [comment]
@swordsreversed Thanks, it worked with your help, I now can stream my voice (mic input) I now, have 2 questions.
1. How can I force the player to start form the last second? Now when I hit the stream url, it starts from the first second of stream not what is streaming NOW. I want my user be able to go back but I want the user can listen what is just streaming now, first.

2. I couldn't get the butt stream an "mp3" file. can you help me to stream an mp3 file instead of my mic input?

thanks.

**Comment by swordsreversed** [comment]
Ok

1. I don't know about this sorry. You would need @ewr to help you.

2. I just played an mp3 through an audio player (winamp) and then set the audio setting in butt to the default audio device. It worked for me.

**Comment by amerireza** [comment]
Thank you @swordsreversed it worked but with real low quality.
