### ISSUE TITLE
I can't connect to server with config/standalone.json settings.

### ISSUE THREAD

**Issue by ogra** [StreamMachine/StreamMachine#99]
I'm new to StreamMachine and tried to broadcast with it, but I can't connect to the server when the server started with config/standalone.json settings.

I started the server with
`./streammachine-cmd --config ./config/standalone.json`
and tried to connect to it with LadioCast (Mac Icecast app).
LadioCast settings are:

```
host: 127.0.0.1
port: 8002
mount: test
user: source
password: testing
encoding format: MP3
```

And I can't connect to the server.

Log:
`4814/sourcein -- debug: Incoming source connection failed to validate before timeout.`

How can I connect to the server and broadcast?

**Comment by nakedsushi** [comment]
StreamMachine doesn't take in a `user` value from the source. And its password field is `source_password`. Can you try passing those in from LadioCast? I'm not too familiar with LadioCast so not sure if there's support for it in StreamMachine.  I'll try it out later and report back.

**Comment by nakedsushi** [comment]
@ogra I downloaded ladiocast and could reproduce your problem. Unfortunately, it seems like a problem with LadioCast. When specifying the 'Icecast' version of the streamer in Ladiocast, the app doesn't actually send any ICY-type headers. StreamMachine requires HTTP authentication headers from the source (what LadioCast is broadcasting).  I don't actually see any password being passed in through the headers, so that's probably why it's not working for you.

Take a look at https://github.com/StreamMachine/StreamMachine/blob/5eb8b5d09bdf4bb95584e77c12427fb2091cfb5c/src/streammachine/master/source_in.coffee#L71 for how StreamMachine authenticates.
